spring:
  application:
    name: Notebook REST
# Descomentar para utilizar postgresql en vez de H2
  datasource:
    host: localhost
    port: 5432
    database: museo_db
    username: museo_user
    password: museo_pass
    url: jdbc:postgresql://database:5432/museo_db
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create  # crea de cero la base de datos cada vez que tiramos el proyecto  (cambiar por validate)
properties:
  clientHost: http://localhost:1234
  jwtSecretKey: h3qlqtvjaq8NEm1AG$2p8qT!^c3AkrE&rno2z8LZWD@qWo40xphNoPQ7j%J197
  jwtValidity: 7200
