# Puerto del microservicio
server.port=8081
  
  # Base URL de The MET API
met.api. base-url=https://collectionapi.metmuseum.org/public/collection/v1
  
  # Logging
logging.level.es.museum.met=INFO
logging.level.org.springframework.web. client=DEBUG
  
  # Nombre del servicio
spring.application.name=met-microservice